// ============================================================
//  LA MAISON DORÉE — Complete Product Catalog (250+ items)
// ============================================================
const PRODUCTS = [
  // ---- CROISSANTS ----
  {id:1,name:"Classic Butter Croissant",category:"croissants",emoji:"🥐",price:85,desc:"Traditional French laminated pastry with 27 layers of pure French butter. Golden, flaky perfection."},
  {id:2,name:"Almond Croissant",category:"croissants",emoji:"🥐",price:120,desc:"Filled with rich almond cream, topped with toasted flaked almonds and powdered sugar."},
  {id:3,name:"Chocolate Croissant",category:"croissants",emoji:"🥐",price:110,desc:"Premium Belgian chocolate batons wrapped in buttery laminated dough."},
  {id:4,name:"Ham & Cheese Croissant",category:"croissants",emoji:"🥐",price:140,desc:"Flaky croissant filled with premium Parisian ham and aged Gruyère cheese."},
  {id:5,name:"Pistachio Croissant",category:"croissants",emoji:"🥐",price:145,desc:"Filled with pistachio frangipane, topped with crushed pistachios and gold dust."},
  {id:6,name:"Matcha Croissant",category:"croissants",emoji:"🥐",price:130,desc:"Ceremonial grade matcha infused croissant with white chocolate filling."},
  {id:7,name:"Kouign-Amann",category:"croissants",emoji:"🥐",price:95,desc:"Breton caramelized cake made with laminated dough and sugar crystals."},
  {id:8,name:"Croissant Sandwich",category:"croissants",emoji:"🥐",price:160,desc:"Sliced croissant with arugula, brie, tomato and dijon mustard."},
  {id:9,name:"Mini Croissant Box (6pc)",category:"croissants",emoji:"🥐",price:350,desc:"Box of 6 mini assorted croissants — perfect for sharing."},
  {id:10,name:"Strawberry Croissant",category:"croissants",emoji:"🥐",price:125,desc:"Filled with fresh strawberry compote and vanilla cream."},

  // ---- BREADS ----
  {id:11,name:"Country Sourdough",category:"breads",emoji:"🍞",price:320,desc:"48-hour fermented sourdough with crackling crust and open crumb. Whole loaf."},
  {id:12,name:"Multigrain Sourdough",category:"breads",emoji:"🍞",price:350,desc:"Seeds and grains sourdough — sunflower, flax, sesame, poppy."},
  {id:13,name:"Rye Bread",category:"breads",emoji:"🍞",price:280,desc:"Dense Scandinavian-style 100% rye bread with caraway seeds."},
  {id:14,name:"Ciabatta",category:"breads",emoji:"🍞",price:180,desc:"Italian flatbread with airy holes and olive oil crust."},
  {id:15,name:"Baguette",category:"breads",emoji:"🥖",price:90,desc:"Classic French baguette — crisp crust, tender crumb. Baked twice daily."},
  {id:16,name:"Brioche Loaf",category:"breads",emoji:"🍞",price:250,desc:"Enriched French bread with eggs and butter. Melt-in-mouth texture."},
  {id:17,name:"Focaccia",category:"breads",emoji:"🍞",price:220,desc:"Rosemary & sea salt Italian flatbread with olive oil pools."},
  {id:18,name:"Challah",category:"breads",emoji:"🍞",price:260,desc:"Six-strand braided Jewish bread with honey glaze."},
  {id:19,name:"Whole Wheat Loaf",category:"breads",emoji:"🍞",price:200,desc:"100% stone-ground whole wheat. Nutty flavor, hearty texture."},
  {id:20,name:"Pão de Queijo",category:"breads",emoji:"🍞",price:60,desc:"Brazilian cheese bread bites — chewy, cheesy, irresistible."},
  {id:21,name:"Epi Baguette",category:"breads",emoji:"🥖",price:110,desc:"Wheat-stalk shaped decorative baguette — stunning and delicious."},
  {id:22,name:"Poolish Baguette",category:"breads",emoji:"🥖",price:100,desc:"Pre-ferment baguette with complex flavor notes."},
  {id:23,name:"Spelt Loaf",category:"breads",emoji:"🍞",price:290,desc:"Ancient grain bread — nutty, nutritious, digestible."},
  {id:24,name:"Olive & Herb Bread",category:"breads",emoji:"🍞",price:310,desc:"Kalamata olives, rosemary, thyme in rustic loaf."},
  {id:25,name:"Pita Bread (4pc)",category:"breads",emoji:"🍞",price:120,desc:"Soft pocket pita breads, freshly baked."},

  // ---- CAKES ----
  {id:26,name:"Fraisier",category:"cakes",emoji:"🎂",price:650,desc:"Classic French strawberry and mousseline cream cake. Serves 4-6."},
  {id:27,name:"Opera Cake",category:"cakes",emoji:"🎂",price:700,desc:"Layers of joconde sponge, coffee buttercream, and ganache."},
  {id:28,name:"Charlotte Royale",category:"cakes",emoji:"🎂",price:750,desc:"Spectacular spiral dome of Swiss roll and bavarian cream."},
  {id:29,name:"Gateau Basque",category:"cakes",emoji:"🎂",price:480,desc:"Basque Country shortcrust cake with cherry jam filling."},
  {id:30,name:"Chocolate Fondant Cake",category:"cakes",emoji:"🎂",price:580,desc:"Intense chocolate cake with molten core. Serves 6."},
  {id:31,name:"Mille-feuille Cake",category:"cakes",emoji:"🎂",price:620,desc:"Thousand-layer puff pastry with vanilla diplomat cream."},
  {id:32,name:"Lemon Drizzle Cake",category:"cakes",emoji:"🎂",price:420,desc:"Zesty lemon cake with crystalline sugar drizzle."},
  {id:33,name:"Black Forest Cake",category:"cakes",emoji:"🎂",price:550,desc:"Classic Schwarzwälder with kirsch cherries and chantilly."},
  {id:34,name:"Tiramisu Cake",category:"cakes",emoji:"🎂",price:580,desc:"Italian classic in cake form — mascarpone, espresso, savoiardi."},
  {id:35,name:"Red Velvet Cake",category:"cakes",emoji:"🎂",price:520,desc:"Velvety cocoa cake with cream cheese frosting."},
  {id:36,name:"Carrot Cake",category:"cakes",emoji:"🎂",price:480,desc:"Spiced carrot cake with walnut and cream cheese frosting."},
  {id:37,name:"Anniversary Cake (Custom)",category:"cakes",emoji:"🎂",price:1200,desc:"Custom decorated celebration cake. Order 48hrs in advance."},
  {id:38,name:"Entremet Aux Fruits",category:"cakes",emoji:"🎂",price:800,desc:"Multi-layer French entremets with seasonal fruit mousse."},
  {id:39,name:"Bûche de Noël Slice",category:"cakes",emoji:"🎂",price:180,desc:"Yule log roll cake slice with mocha cream."},
  {id:40,name:"Basque Burnt Cheesecake",category:"cakes",emoji:"🎂",price:520,desc:"Rustic burnt top cheesecake — creamy, caramelized, ethereal."},
  {id:41,name:"Flourless Chocolate Cake",category:"cakes",emoji:"🎂",price:490,desc:"Dense, fudgy, gluten-free. Topped with cocoa dusting."},
  {id:42,name:"Victoria Sponge",category:"cakes",emoji:"🎂",price:440,desc:"British classic — light sponge with jam and clotted cream."},
  {id:43,name:"Japanese Cheesecake",category:"cakes",emoji:"🎂",price:560,desc:"Jiggly, cloud-like Japanese soufflé cheesecake."},
  {id:44,name:"Strawberry Shortcake",category:"cakes",emoji:"🎂",price:480,desc:"Light génoise with fresh strawberries and chantilly."},
  {id:45,name:"Sachertorte",category:"cakes",emoji:"🎂",price:600,desc:"Viennese chocolate cake with apricot jam glaze."},

  // ---- PASTRIES ----
  {id:46,name:"Classic Éclair",category:"pastries",emoji:"🍫",price:110,desc:"Choux pastry filled with vanilla crème pâtissière, chocolate glaze."},
  {id:47,name:"Coffee Éclair",category:"pastries",emoji:"🍫",price:115,desc:"Espresso cream filled éclair with coffee mirror glaze."},
  {id:48,name:"Matcha Éclair",category:"pastries",emoji:"🍫",price:120,desc:"Japanese matcha cream with white chocolate glaze."},
  {id:49,name:"Caramel Éclair",category:"pastries",emoji:"🍫",price:115,desc:"Salted caramel cream with caramelized glaze."},
  {id:50,name:"Paris-Brest",category:"pastries",emoji:"🍫",price:180,desc:"Choux ring filled with praline mousseline cream."},
  {id:51,name:"Saint-Honoré",category:"pastries",emoji:"🍫",price:200,desc:"Puff and choux pastry crown with caramel profiteroles."},
  {id:52,name:"Profiteroles (3pc)",category:"pastries",emoji:"🍫",price:150,desc:"Cream puffs with vanilla cream and warm chocolate sauce."},
  {id:53,name:"Religieuse",category:"pastries",emoji:"🍫",price:140,desc:"Two-tiered choux pastry — cream, ganache, collar decoration."},
  {id:54,name:"Mille-feuille Slice",category:"pastries",emoji:"🥐",price:160,desc:"Individual portion of classic thousand-layer pastry."},
  {id:55,name:"Palmier",category:"pastries",emoji:"🥐",price:55,desc:"Caramelized puff pastry heart — crispy, sweet, elegant."},
  {id:56,name:"Financier",category:"pastries",emoji:"🍰",price:70,desc:"French brown butter almond cake — nutty, golden, addictive."},
  {id:57,name:"Canelé",category:"pastries",emoji:"🍰",price:80,desc:"Bordeaux pastry — caramelized crust, vanilla custard heart."},
  {id:58,name:"Kouglof",category:"pastries",emoji:"🍰",price:320,desc:"Alsatian yeasted cake with raisins and almonds."},
  {id:59,name:"Galette des Rois",category:"pastries",emoji:"🍰",price:280,desc:"Puff pastry king cake with almond frangipane filling."},
  {id:60,name:"Chausson aux Pommes",category:"pastries",emoji:"🥐",price:95,desc:"French apple turnover with cinnamon compote filling."},
  {id:61,name:"Strawberry Tart",category:"pastries",emoji:"🍓",price:180,desc:"Sweet pastry shell, vanilla cream, fresh seasonal strawberries."},
  {id:62,name:"Cream Horn",category:"pastries",emoji:"🥐",price:85,desc:"Flaky puff pastry cone filled with whipped cream."},
  {id:63,name:"Danish Pastry",category:"pastries",emoji:"🥐",price:100,desc:"Buttery laminated Danish with fruit and custard."},
  {id:64,name:"Strudel Slice",category:"pastries",emoji:"🥐",price:120,desc:"Viennese apple strudel with cinnamon and raisins."},
  {id:65,name:"Baklava (2pc)",category:"pastries",emoji:"🍰",price:140,desc:"Honey-soaked phyllo with pistachios and rose water."},

  // ---- COOKIES ----
  {id:66,name:"Classic Chocolate Chip",category:"cookies",emoji:"🍪",price:55,desc:"Signature cookie with Valrhona chocolate chips and fleur de sel."},
  {id:67,name:"Double Chocolate",category:"cookies",emoji:"🍪",price:65,desc:"Intense cocoa cookie with milk and dark chocolate chunks."},
  {id:68,name:"Shortbread Rounds",category:"cookies",emoji:"🍪",price:45,desc:"Buttery Scottish shortbread — crisp, pure, classic."},
  {id:69,name:"Viennese Whirls",category:"cookies",emoji:"🍪",price:70,desc:"Piped butter cookies sandwiched with jam and buttercream."},
  {id:70,name:"Florentines",category:"cookies",emoji:"🍪",price:75,desc:"Caramelized almond and fruit lace cookies with dark chocolate."},
  {id:71,name:"Tuiles",category:"cookies",emoji:"🍪",price:55,desc:"Delicate curved almond wafers — paper thin, ethereal."},
  {id:72,name:"Linzer Cookie",category:"cookies",emoji:"🍪",price:65,desc:"Almond dough cookies sandwiched with raspberry jam."},
  {id:73,name:"Biscotti (3pc)",category:"cookies",emoji:"🍪",price:90,desc:"Twice-baked Italian almond biscotti for coffee dipping."},
  {id:74,name:"Snickerdoodle",category:"cookies",emoji:"🍪",price:50,desc:"Cinnamon-sugar rolled soft cookies."},
  {id:75,name:"Pistachio Sandies",category:"cookies",emoji:"🍪",price:70,desc:"Crumbly pistachio melt-aways with powdered sugar."},
  {id:76,name:"Amaretti",category:"cookies",emoji:"🍪",price:80,desc:"Crispy Italian almond macaroons with bitter almond flavor."},
  {id:77,name:"Speculoos",category:"cookies",emoji:"🍪",price:60,desc:"Belgian spiced windmill cookies — crunchy, warming."},
  {id:78,name:"Oat & Raisin",category:"cookies",emoji:"🍪",price:50,desc:"Hearty oat cookies with plump golden raisins."},
  {id:79,name:"Salted Caramel Cookie",category:"cookies",emoji:"🍪",price:65,desc:"Chewy caramel cookie with fleur de sel on top."},
  {id:80,name:"Cookie Box (12pc)",category:"cookies",emoji:"🍪",price:650,desc:"Assorted premium cookie gift box — 12 artisan cookies."},

  // ---- MACARONS ----
  {id:81,name:"Raspberry Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Vibrant raspberry ganache in almond meringue shells."},
  {id:82,name:"Salted Caramel Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Fleur de sel caramel buttercream — the crowd favourite."},
  {id:83,name:"Pistachio Macaron",category:"macarons",emoji:"🍬",price:90,desc:"Ground pistachio shells with pistachio praline cream."},
  {id:84,name:"Rose Lychee Macaron",category:"macarons",emoji:"🍬",price:90,desc:"Iconic Ispahan combination — rose, lychee, raspberry."},
  {id:85,name:"Lavender Honey Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Provençal lavender with wildflower honey ganache."},
  {id:86,name:"Chocolate Macaron",category:"macarons",emoji:"🍬",price:85,desc:"70% dark Valrhona ganache — intense and sophisticated."},
  {id:87,name:"Lemon Macaron",category:"macarons",emoji:"🍬",price:80,desc:"Tart lemon curd with lemon buttercream filling."},
  {id:88,name:"Vanilla Macaron",category:"macarons",emoji:"🍬",price:80,desc:"Madagascar bourbon vanilla bean ganache."},
  {id:89,name:"Blackcurrant Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Intense cassis ganache with violet notes."},
  {id:90,name:"Coffee Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Espresso ganache for the coffee lover."},
  {id:91,name:"Matcha Macaron",category:"macarons",emoji:"🍬",price:90,desc:"Ceremonial matcha white chocolate ganache."},
  {id:92,name:"Macaron Box (6pc)",category:"macarons",emoji:"🍬",price:480,desc:"Curated selection of 6 seasonal macarons."},
  {id:93,name:"Macaron Box (12pc)",category:"macarons",emoji:"🍬",price:890,desc:"Luxury gift box of 12 assorted macarons."},
  {id:94,name:"Passion Fruit Macaron",category:"macarons",emoji:"🍬",price:90,desc:"Tropical passion fruit and dark chocolate ganache."},
  {id:95,name:"Earl Grey Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Bergamot-infused ganache from premium Earl Grey."},

  // ---- TARTS ----
  {id:96,name:"Lemon Tart",category:"tarts",emoji:"🍋",price:195,desc:"Brûléed lemon curd in crisp pâte sucrée shell."},
  {id:97,name:"Chocolate Tart",category:"tarts",emoji:"🍫",price:210,desc:"Silky Valrhona ganache in cocoa pastry shell."},
  {id:98,name:"Fruit Tart",category:"tarts",emoji:"🍓",price:230,desc:"Seasonal fruits on vanilla cream in golden pastry shell."},
  {id:99,name:"Frangipane Tart",category:"tarts",emoji:"🍰",price:200,desc:"Almond cream in sweet pastry with seasonal fruit topping."},
  {id:100,name:"Caramelized Onion Tart",category:"tarts",emoji:"🧅",price:180,desc:"Savory tart with caramelized onions and Gruyère."},
  {id:101,name:"Quiche Lorraine",category:"tarts",emoji:"🥧",price:175,desc:"Classic French quiche with lardon and cream."},
  {id:102,name:"Spinach & Feta Quiche",category:"tarts",emoji:"🥧",price:175,desc:"Wilted spinach and Greek feta in egg custard."},
  {id:103,name:"Blood Orange Tart",category:"tarts",emoji:"🍊",price:215,desc:"Seasonal blood orange curd with caramel meringue."},
  {id:104,name:"Mango Tart",category:"tarts",emoji:"🥭",price:220,desc:"Alphonso mango cream in tropical pastry shell."},
  {id:105,name:"Walnut Tart",category:"tarts",emoji:"🌰",price:190,desc:"Toasted walnut and dark honey filling in shortcrust."},
  {id:106,name:"Apple Tart Tatin",category:"tarts",emoji:"🍎",price:220,desc:"Caramelized apple upside-down tart — Normandy classic."},
  {id:107,name:"Pear & Almond Tart",category:"tarts",emoji:"🍐",price:205,desc:"Poached pear with almond frangipane filling."},

  // ---- MUFFINS ----
  {id:108,name:"Classic Blueberry Muffin",category:"muffins",emoji:"🫐",price:90,desc:"Bursting with wild blueberries, lemon zest, streusel top."},
  {id:109,name:"Chocolate Chunk Muffin",category:"muffins",emoji:"🍫",price:95,desc:"Triple chocolate — cocoa base, dark chunks, chocolate glaze."},
  {id:110,name:"Bran & Raisin Muffin",category:"muffins",emoji:"🍞",price:75,desc:"Wholesome wheat bran muffin with plump raisins."},
  {id:111,name:"Banana Walnut Muffin",category:"muffins",emoji:"🍌",price:85,desc:"Moist banana bread muffin with crunchy walnut pieces."},
  {id:112,name:"Cranberry Orange Muffin",category:"muffins",emoji:"🍊",price:90,desc:"Tart cranberries with orange zest and glaze."},
  {id:113,name:"Lemon Poppy Seed Muffin",category:"muffins",emoji:"🍋",price:85,desc:"Bright lemon muffin with poppy seeds and lemon drizzle."},
  {id:114,name:"Carrot & Ginger Muffin",category:"muffins",emoji:"🥕",price:85,desc:"Spiced carrot with fresh ginger and cream cheese frosting."},
  {id:115,name:"Corn Muffin",category:"muffins",emoji:"🌽",price:70,desc:"Sweet cornbread muffin with honey butter."},
  {id:116,name:"Zucchini Muffin",category:"muffins",emoji:"🥗",price:80,desc:"Savory zucchini, feta and herb muffin."},
  {id:117,name:"Red Velvet Muffin",category:"muffins",emoji:"❤️",price:95,desc:"Cocoa red velvet muffin with cream cheese topping."},
  {id:118,name:"Pumpkin Spice Muffin",category:"muffins",emoji:"🎃",price:90,desc:"Pumpkin purée with cinnamon, nutmeg, and pepitas."},
  {id:119,name:"Morning Glory Muffin",category:"muffins",emoji:"🌻",price:90,desc:"Apple, carrot, coconut, raisin — the ultimate morning muffin."},

  // ---- BEVERAGES ----
  {id:120,name:"Café au Lait",category:"beverages",emoji:"☕",price:120,desc:"Freshly brewed French press coffee with steamed whole milk."},
  {id:121,name:"Espresso",category:"beverages",emoji:"☕",price:80,desc:"Single origin Ethiopian espresso — floral, complex, bright."},
  {id:122,name:"Cortado",category:"beverages",emoji:"☕",price:110,desc:"Equal parts espresso and warm milk — balanced perfection."},
  {id:123,name:"Flat White",category:"beverages",emoji:"☕",price:130,desc:"Ristretto base with microfoam milk — velvety texture."},
  {id:124,name:"Latte Macchiato",category:"beverages",emoji:"☕",price:140,desc:"Layered espresso and steamed milk with foam crown."},
  {id:125,name:"Chai Latte",category:"beverages",emoji:"🍵",price:130,desc:"House-spiced masala chai with oat milk."},
  {id:126,name:"Matcha Latte",category:"beverages",emoji:"🍵",price:150,desc:"Ceremonial grade matcha whisked with steamed milk."},
  {id:127,name:"Hot Chocolate",category:"beverages",emoji:"🍫",price:160,desc:"Valrhona 70% dark chocolate — thick, rich, Parisian style."},
  {id:128,name:"Cold Brew",category:"beverages",emoji:"🧊",price:160,desc:"18-hour cold steeped coffee — smooth, concentrated, refreshing."},
  {id:129,name:"Iced Latte",category:"beverages",emoji:"🧊",price:160,desc:"Espresso over ice with cold whole milk."},
  {id:130,name:"Croissant + Coffee Set",category:"beverages",emoji:"☕",price:180,desc:"Classic butter croissant paired with café au lait."},
  {id:131,name:"Fresh Orange Juice",category:"beverages",emoji:"🍊",price:140,desc:"Hand-pressed Nagpur oranges — seasonal and fresh."},
  {id:132,name:"Rose Lemonade",category:"beverages",emoji:"🌹",price:120,desc:"House lemonade with rose syrup and mint."},
  {id:133,name:"Sparkling Water",category:"beverages",emoji:"💧",price:60,desc:"Premium Italian sparkling mineral water."},
  {id:134,name:"Affogato",category:"beverages",emoji:"☕",price:180,desc:"Vanilla gelato drowned in hot espresso — divine contrast."},

  // ---- SAVORY ----
  {id:135,name:"Croque Monsieur",category:"savory",emoji:"🥪",price:220,desc:"Classic French toasted sandwich with béchamel and Gruyère."},
  {id:136,name:"Croque Madame",category:"savory",emoji:"🥚",price:240,desc:"Croque Monsieur crowned with a perfectly fried egg."},
  {id:137,name:"Smoked Salmon Bagel",category:"savory",emoji:"🥯",price:280,desc:"House-baked bagel with cream cheese, capers, red onion."},
  {id:138,name:"Avocado Toast",category:"savory",emoji:"🥑",price:200,desc:"Sourdough with smashed avocado, microgreens, chilli flakes."},
  {id:139,name:"Tomato Bruschetta",category:"savory",emoji:"🍅",price:160,desc:"Grilled ciabatta with heirloom tomatoes, basil, olive oil."},
  {id:140,name:"Mushroom Galette",category:"savory",emoji:"🍄",price:240,desc:"Buckwheat crêpe filled with wild mushrooms and Gruyère."},
  {id:141,name:"Onion Soup",category:"savory",emoji:"🧅",price:220,desc:"Classic French onion soup with Gruyère crouton lid."},
  {id:142,name:"Soup du Jour",category:"savory",emoji:"🍲",price:180,desc:"Chef's seasonal soup served with sourdough croutons."},
  {id:143,name:"Charcuterie Board",category:"savory",emoji:"🧀",price:580,desc:"Selection of cured meats, artisan cheeses, pickles and bread."},
  {id:144,name:"Cheese Platter",category:"savory",emoji:"🧀",price:480,desc:"Five artisan cheeses with honey, walnuts and crackers."},
  {id:145,name:"Egg Mayonnaise Sandwich",category:"savory",emoji:"🥚",price:160,desc:"Classic egg mayo on soft brioche with watercress."},
  {id:146,name:"Chicken Pesto Wrap",category:"savory",emoji:"🫔",price:250,desc:"Grilled chicken, house pesto, roasted peppers in spinach wrap."},
  {id:147,name:"Caprese Panini",category:"savory",emoji:"🍅",price:220,desc:"Fresh mozzarella, heirloom tomato, basil in ciabatta."},
  {id:148,name:"Club Sandwich",category:"savory",emoji:"🥪",price:280,desc:"Triple-decker with chicken, turkey, bacon, lettuce, tomato."},
  {id:149,name:"Vegetable Frittata",category:"savory",emoji:"🥚",price:180,desc:"Italian baked omelette with seasonal vegetables."},
  {id:150,name:"Smoked Salmon Quiche",category:"savory",emoji:"🥧",price:220,desc:"Scottish smoked salmon and dill in egg custard."},

  // ---- SEASONAL ----
  {id:151,name:"Mango & Passion Tart",category:"seasonal",emoji:"🥭",price:260,desc:"Summer special — Alphonso mango with passion fruit mousse."},
  {id:152,name:"Strawberry Basil Cake",category:"seasonal",emoji:"🍓",price:540,desc:"Fresh strawberry compote with basil cream — spring special."},
  {id:153,name:"Fig & Walnut Bread",category:"seasonal",emoji:"🌿",price:340,desc:"Harvest season — dried figs and walnuts in country loaf."},
  {id:154,name:"Pumpkin Cheesecake",category:"seasonal",emoji:"🎃",price:560,desc:"Autumn spiced pumpkin cheesecake with ginger crust."},
  {id:155,name:"Winter Spice Cake",category:"seasonal",emoji:"❄️",price:520,desc:"Cardamom, cinnamon, star anise — warming winter cake."},
  {id:156,name:"Gulab Jamun Tart",category:"seasonal",emoji:"🌹",price:240,desc:"East-meets-West fusion — gulab jamun in pastry shell."},
  {id:157,name:"Pistachio Rose Cake",category:"seasonal",emoji:"🌸",price:580,desc:"Pistachio sponge with rose water cream — Persian inspired."},
  {id:158,name:"Diwali Mithai Box",category:"seasonal",emoji:"✨",price:890,desc:"Festive box with French pastry interpretations of Indian sweets."},
  {id:159,name:"Kesar Pista Macaron",category:"seasonal",emoji:"🍬",price:95,desc:"Saffron and pistachio fusion macaron — exclusively Indian."},
  {id:160,name:"Thandai Panna Cotta",category:"seasonal",emoji:"🌺",price:180,desc:"Holi special — thandai-spiced panna cotta."},

  // ---- MORE PASTRIES ---- (continuing variety)
  {id:161,name:"Palmier Rose",category:"pastries",emoji:"🥐",price:60,desc:"Rose petal and vanilla palmier cookies."},
  {id:162,name:"Chocolate Soufflé",category:"pastries",emoji:"🍫",price:250,desc:"Individual hot chocolate soufflé. Order 20 mins ahead."},
  {id:163,name:"Crème Brûlée",category:"pastries",emoji:"🍮",price:220,desc:"Classic vanilla bean crème brûlée with caramelized top."},
  {id:164,name:"Pots de Crème",category:"pastries",emoji:"🍮",price:200,desc:"Silky chocolate custard pots — rich and indulgent."},
  {id:165,name:"Île Flottante",category:"pastries",emoji:"☁️",price:190,desc:"Floating island meringue on crème anglaise with praline."},
  {id:166,name:"Tarte au Citron Vert",category:"pastries",emoji:"🍋",price:200,desc:"Lime curd tart with lime zest meringue peaks."},
  {id:167,name:"Praline Choux",category:"pastries",emoji:"🍫",price:130,desc:"Hazelnut praline filled choux puffs with chocolate glaze."},
  {id:168,name:"Marron Glacé",category:"pastries",emoji:"🌰",price:160,desc:"Candied chestnuts in simple syrup — French confection."},
  {id:169,name:"Pâte de Fruits (4pc)",category:"pastries",emoji:"🍬",price:180,desc:"Concentrated fruit jellies — raspberry, passion, apricot, blackcurrant."},
  {id:170,name:"Truffles (4pc)",category:"pastries",emoji:"🍫",price:280,desc:"Handrolled dark chocolate truffles dusted in cocoa."},

  // ---- MORE BREADS ----
  {id:171,name:"Pumpernickel",category:"breads",emoji:"🍞",price:260,desc:"German dark rye bread — dense, moist, earthy."},
  {id:172,name:"Sun-dried Tomato Focaccia",category:"breads",emoji:"🍞",price:240,desc:"Focaccia with sun-dried tomatoes, olives, capers."},
  {id:173,name:"Jalapeno Cheese Bread",category:"breads",emoji:"🌶️",price:290,desc:"Soft pull-apart bread with jalapeños and cheddar."},
  {id:174,name:"Pretzels (2pc)",category:"breads",emoji:"🥨",price:110,desc:"Authentic German pretzels with coarse salt and mustard."},
  {id:175,name:"Naan Bread (2pc)",category:"breads",emoji:"🫓",price:90,desc:"Tandoor-inspired soft flatbread with ghee."},
  {id:176,name:"Pesto Bread Roll",category:"breads",emoji:"🍞",price:80,desc:"Basil pesto swirl in soft milk bread dough."},
  {id:177,name:"Garlic Bread",category:"breads",emoji:"🥖",price:90,desc:"Baguette with compound herb garlic butter."},
  {id:178,name:"Seeded Roll",category:"breads",emoji:"🍞",price:55,desc:"Individual crusty roll with sesame, poppy and sunflower seeds."},
  {id:179,name:"Milk Bread Loaf",category:"breads",emoji:"🍞",price:180,desc:"Japanese shokupan — pillowy soft, slightly sweet."},
  {id:180,name:"Oat Tin Loaf",category:"breads",emoji:"🍞",price:220,desc:"Rolled oat topped wholegrain loaf for healthy mornings."},

  // ---- MORE CAKES ----
  {id:181,name:"Chocolate Lava Cake",category:"cakes",emoji:"🎂",price:290,desc:"Individual warm chocolate cake with molten center."},
  {id:182,name:"Bento Cake",category:"cakes",emoji:"🎂",price:380,desc:"Mini custom cake for one — with personalized message."},
  {id:183,name:"Naked Cake",category:"cakes",emoji:"🎂",price:680,desc:"Rustic unfrosted layer cake with seasonal flowers."},
  {id:184,name:"Mirror Glaze Cake",category:"cakes",emoji:"🎂",price:850,desc:"Stunning reflective glaze entremets — showstopper."},
  {id:185,name:"Geode Crystal Cake",category:"cakes",emoji:"🎂",price:950,desc:"Rock candy crystal geode — edible art. Order 72hrs ahead."},
  {id:186,name:"Tres Leches",category:"cakes",emoji:"🎂",price:420,desc:"Latin American milk-soaked sponge with whipped cream."},
  {id:187,name:"Trifle",category:"cakes",emoji:"🎂",price:380,desc:"Layered English trifle with custard, cream, fruit and sponge."},
  {id:188,name:"Pavlova",category:"cakes",emoji:"🎂",price:460,desc:"New Zealand meringue with cream and seasonal berries."},
  {id:189,name:"Dobos Torte",category:"cakes",emoji:"🎂",price:580,desc:"Hungarian seven-layer sponge with chocolate buttercream."},
  {id:190,name:"Mousse au Chocolat",category:"cakes",emoji:"🎂",price:320,desc:"Classic French chocolate mousse — airy, intense, perfect."},

  // ---- MORE COOKIES ----
  {id:191,name:"Madeleines (4pc)",category:"cookies",emoji:"🍪",price:140,desc:"Shell-shaped French butter cakes — lemon zest, classic."},
  {id:192,name:"Langue de Chat",category:"cookies",emoji:"🍪",price:65,desc:"Delicate cat's tongue biscuits — light, crispy."},
  {id:193,name:"Sablés Bretons",category:"cookies",emoji:"🍪",price:80,desc:"Breton butter biscuits — crumbly, salty, addictive."},
  {id:194,name:"Chocolate Dipped Shortbread",category:"cookies",emoji:"🍪",price:75,desc:"Shortbread half-dipped in dark Valrhona chocolate."},
  {id:195,name:"Rainbow Sugar Cookies",category:"cookies",emoji:"🍪",price:80,desc:"Decorated sugar cookies — colourful, fun, delicious."},
  {id:196,name:"Pfeffernüsse",category:"cookies",emoji:"🍪",price:70,desc:"German peppercorn spice cookies with sugar glaze."},
  {id:197,name:"Alfajores (2pc)",category:"cookies",emoji:"🍪",price:110,desc:"South American dulce de leche sandwiched cookies."},
  {id:198,name:"Fortune Cookies (4pc)",category:"cookies",emoji:"🍪",price:120,desc:"Crispy fortune cookies with custom messages."},
  {id:199,name:"Meringue Kisses (6pc)",category:"cookies",emoji:"🍪",price:160,desc:"Pastel French meringue kisses — light as air."},
  {id:200,name:"Cookie Gift Tin",category:"cookies",emoji:"🍪",price:1200,desc:"Beautiful tin of 20 assorted premium cookies — perfect gift."},

  // ---- MORE MACARONS ----
  {id:201,name:"Coconut Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Toasted coconut and mango cream macaron."},
  {id:202,name:"Basil & Strawberry Macaron",category:"macarons",emoji:"🍬",price:90,desc:"Unexpected herb and fruit combination — memorable."},
  {id:203,name:"Caramelized Fig Macaron",category:"macarons",emoji:"🍬",price:90,desc:"Rich fig jam and honey cream macaron."},
  {id:204,name:"Hazelnut Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Praline hazelnut cream — like Nutella, elevated."},
  {id:205,name:"Mint Chocolate Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Fresh mint ganache with dark chocolate shells."},

  // ---- MORE MUFFINS ----
  {id:206,name:"Espresso Muffin",category:"muffins",emoji:"☕",price:90,desc:"Coffee-infused muffin with espresso drizzle."},
  {id:207,name:"Almond Berry Muffin",category:"muffins",emoji:"🫐",price:95,desc:"Almond flour muffin with mixed berry compote center."},
  {id:208,name:"Coconut Muffin",category:"muffins",emoji:"🥥",price:85,desc:"Toasted coconut muffin with lime glaze."},
  {id:209,name:"Hazelnut Muffin",category:"muffins",emoji:"🌰",price:90,desc:"Gianduja hazelnut chocolate muffin with crumble."},
  {id:210,name:"Apple Cinnamon Muffin",category:"muffins",emoji:"🍎",price:85,desc:"Chunks of apple and warm cinnamon with sugar crust."},

  // ---- MORE SAVORY ----
  {id:211,name:"Spinach & Ricotta Pastry",category:"savory",emoji:"🥬",price:160,desc:"Flaky pastry parcel with creamy ricotta and spinach."},
  {id:212,name:"Mushroom Tart",category:"savory",emoji:"🍄",price:190,desc:"Wild mushroom duxelles in crisp shortcrust shell."},
  {id:213,name:"Prawn Toast",category:"savory",emoji:"🦐",price:180,desc:"Sesame-crusted shrimp toast — French-Asian fusion."},
  {id:214,name:"Tomato Galette",category:"savory",emoji:"🍅",price:200,desc:"Heirloom tomato free-form tart with herbed ricotta."},
  {id:215,name:"Canapé Set (12pc)",category:"savory",emoji:"🍱",price:680,desc:"Elegant canapés — smoked salmon, goat cheese, bruschetta."},
  {id:216,name:"Gougères (4pc)",category:"savory",emoji:"🧀",price:160,desc:"French cheese puffs with Gruyère and herbs."},
  {id:217,name:"Tapenade Toast",category:"savory",emoji:"🫒",price:140,desc:"Sourdough with Provençal olive tapenade and microherbs."},
  {id:218,name:"Beet & Goat Cheese Tart",category:"savory",emoji:"🟣",price:210,desc:"Roasted beet with fresh goat cheese and thyme."},
  {id:219,name:"French Onion Focaccia",category:"savory",emoji:"🧅",price:190,desc:"Caramelized onion and Gruyère topped focaccia."},
  {id:220,name:"Prosciutto Melon Board",category:"savory",emoji:"🍈",price:380,desc:"Italian prosciutto with cantaloupe melon and basil oil."},

  // ---- MORE SEASONAL ----
  {id:221,name:"Christmas Stollen",category:"seasonal",emoji:"🎄",price:480,desc:"German Christmas bread with marzipan, fruits, spices."},
  {id:222,name:"Hot Cross Buns (4pc)",category:"seasonal",emoji:"✝️",price:200,desc:"Easter spiced buns with cross and raisin filling."},
  {id:223,name:"Eid Baklava Box",category:"seasonal",emoji:"🌙",price:680,desc:"Special Eid selection of rose water and pistachio baklava."},
  {id:224,name:"Valentine Heart Cake",category:"seasonal",emoji:"❤️",price:680,desc:"Raspberry heart-shaped entremet for Valentine's Day."},
  {id:225,name:"Holi Thandai Cake",category:"seasonal",emoji:"🎨",price:560,desc:"Holi special spiced thandai layered cake."},
  {id:226,name:"Monsoon Special Bread",category:"seasonal",emoji:"🌧️",price:300,desc:"Masala chai-spiced pull-apart bread — rainy day comfort."},
  {id:227,name:"Summer Berry Pavlova",category:"seasonal",emoji:"🍓",price:490,desc:"Seasonal peak — summer berries on crispy meringue."},
  {id:228,name:"Pumpkin Bread Loaf",category:"seasonal",emoji:"🎃",price:280,desc:"Autumn pumpkin spice loaf with pepitas and honey."},
  {id:229,name:"New Year Champagne Cake",category:"seasonal",emoji:"🥂",price:780,desc:"Champagne mousse cake for celebrations."},
  {id:230,name:"Teacher's Day Cookie Set",category:"seasonal",emoji:"🎁",price:480,desc:"Decorated cookie gift set — perfect appreciation gift."},

  // ---- EXTRA VARIETY ----
  {id:231,name:"Choco Lava Tart",category:"tarts",emoji:"🍫",price:240,desc:"Warm dark chocolate lava in crispy tart shell."},
  {id:232,name:"Breton Shortcake",category:"pastries",emoji:"🍰",price:120,desc:"Classic French butter cake — thick, rich, golden."},
  {id:233,name:"Coffee Walnut Cake",category:"cakes",emoji:"🎂",price:480,desc:"Coffee sponge with walnut praline buttercream."},
  {id:234,name:"Honey Almond Cake",category:"cakes",emoji:"🎂",price:460,desc:"Delicate almond sponge with wildflower honey glaze."},
  {id:235,name:"Pistachio Tart",category:"tarts",emoji:"🍬",price:220,desc:"Frangipane pistachio cream in buttery pastry."},
  {id:236,name:"Espresso Macaron",category:"macarons",emoji:"🍬",price:85,desc:"Double espresso ganache — for serious coffee lovers."},
  {id:237,name:"Sea Salt Brownie",category:"pastries",emoji:"🍫",price:110,desc:"Fudgy Valrhona brownie with fleur de sel."},
  {id:238,name:"Cannelé de Bordeaux",category:"pastries",emoji:"🍰",price:85,desc:"Bordeaux specialty — caramelized exterior, custardy center."},
  {id:239,name:"Kouign-Amann Individual",category:"croissants",emoji:"🥐",price:130,desc:"Personal-sized caramelized butter cake — crispy, layered."},
  {id:240,name:"Danish Pastry Box (4pc)",category:"pastries",emoji:"🥐",price:380,desc:"4 assorted Viennoiserie pastries in gift box."},
  {id:241,name:"Choco Hazelnut Tart",category:"tarts",emoji:"🍫",price:215,desc:"Nutella-inspired chocolate hazelnut cream tart."},
  {id:242,name:"Strawberry Mille-feuille",category:"pastries",emoji:"🍓",price:195,desc:"Fresh strawberry and Chantilly thousand-layer pastry."},
  {id:243,name:"Pistachio Brioche",category:"breads",emoji:"🍞",price:160,desc:"Enriched brioche dough with pistachio swirl."},
  {id:244,name:"Cinnamon Roll",category:"pastries",emoji:"🌀",price:120,desc:"Soft cinnamon roll with cream cheese frosting."},
  {id:245,name:"Cardamom Roll",category:"pastries",emoji:"🌀",price:125,desc:"Swedish-inspired cardamom bun — fragrant, soft."},
  {id:246,name:"Focaccia di Recco",category:"savory",emoji:"🧀",price:260,desc:"Ligurian cheese-filled paper-thin focaccia."},
  {id:247,name:"Truffle Grilled Cheese",category:"savory",emoji:"🧀",price:320,desc:"Sourdough with black truffle and aged Gruyère."},
  {id:248,name:"Chocolate Babka",category:"breads",emoji:"🍞",price:320,desc:"Twisted enriched bread with dark chocolate swirl."},
  {id:249,name:"Cinnamon Babka",category:"breads",emoji:"🍞",price:300,desc:"Cinnamon sugar twisted bread — beautiful spiral."},
  {id:250,name:"Morning Pastry Basket",category:"pastries",emoji:"🧺",price:480,desc:"Baker's selection — croissant, pain au chocolat, danish, muffin."},
  {id:251,name:"Croissant au Jambon",category:"croissants",emoji:"🥐",price:150,desc:"Buttery croissant with premium ham and dijon."},
  {id:252,name:"Breakfast Box",category:"savory",emoji:"🍱",price:520,desc:"Complete breakfast — pastry, fruit, yogurt, coffee."},
  {id:253,name:"Afternoon Tea Set",category:"pastries",emoji:"🫖",price:680,desc:"Classic afternoon tea — scones, finger sandwiches, pastries, tea."},
  {id:254,name:"Chef's Special Box",category:"seasonal",emoji:"⭐",price:1200,desc:"Weekly chef's special selection — limited, premium, exclusive."},
  {id:255,name:"Sourdough Starter Kit",category:"breads",emoji:"🍞",price:350,desc:"Take home sourdough starter with recipe card — bake at home!"},
];

// Indian Pincode Database (sample)
const PINCODES = {
  "400001": { city: "Mumbai", state: "Maharashtra" },
  "400002": { city: "Mumbai", state: "Maharashtra" },
  "400050": { city: "Mumbai", state: "Maharashtra" },
  "400051": { city: "Bandra West, Mumbai", state: "Maharashtra" },
  "400052": { city: "Bandra East, Mumbai", state: "Maharashtra" },
  "400053": { city: "Khar West, Mumbai", state: "Maharashtra" },
  "400054": { city: "Santacruz West, Mumbai", state: "Maharashtra" },
  "400055": { city: "Santacruz East, Mumbai", state: "Maharashtra" },
  "400056": { city: "Vile Parle West, Mumbai", state: "Maharashtra" },
  "400057": { city: "Andheri West, Mumbai", state: "Maharashtra" },
  "400058": { city: "Andheri East, Mumbai", state: "Maharashtra" },
  "400059": { city: "Goregaon West, Mumbai", state: "Maharashtra" },
  "400060": { city: "Goregaon East, Mumbai", state: "Maharashtra" },
  "400061": { city: "Malad West, Mumbai", state: "Maharashtra" },
  "400062": { city: "Malad East, Mumbai", state: "Maharashtra" },
  "400063": { city: "Kandivali West, Mumbai", state: "Maharashtra" },
  "400064": { city: "Kandivali East, Mumbai", state: "Maharashtra" },
  "400070": { city: "Ghatkopar East, Mumbai", state: "Maharashtra" },
  "400071": { city: "Ghatkopar West, Mumbai", state: "Maharashtra" },
  "400080": { city: "Powai, Mumbai", state: "Maharashtra" },
  "400081": { city: "Vikhroli, Mumbai", state: "Maharashtra" },
  "400086": { city: "Chembur, Mumbai", state: "Maharashtra" },
  "400092": { city: "Thane", state: "Maharashtra" },
  "400601": { city: "Thane West", state: "Maharashtra" },
  "110001": { city: "New Delhi", state: "Delhi" },
  "110011": { city: "New Delhi", state: "Delhi" },
  "110020": { city: "New Delhi", state: "Delhi" },
  "560001": { city: "Bengaluru", state: "Karnataka" },
  "560025": { city: "Indiranagar, Bengaluru", state: "Karnataka" },
  "560038": { city: "Koramangala, Bengaluru", state: "Karnataka" },
  "600001": { city: "Chennai", state: "Tamil Nadu" },
  "700001": { city: "Kolkata", state: "West Bengal" },
  "500001": { city: "Hyderabad", state: "Telangana" },
  "411001": { city: "Pune", state: "Maharashtra" },
  "411004": { city: "Kothrud, Pune", state: "Maharashtra" },
  "380001": { city: "Ahmedabad", state: "Gujarat" },
  "302001": { city: "Jaipur", state: "Rajasthan" },
  "226001": { city: "Lucknow", state: "Uttar Pradesh" },
};
